platform:ios,'12.0'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
use_frameworks!
inhibit_all_warnings!
target 'LanguageTest' do
   pod 'SnapKit','~> 5.6.0'
   pod 'Reusable','~> 4.1.2'
   pod 'ZFPlayer/AVPlayer', '~> 4.0'
   pod 'ObjectMapper'
pod 'AFNetworking'
pod 'Masonry'
pod 'YYKit'
pod 'ReactiveObjC', '~> 3.1.1'
#pod 'SHEmotionKeyboard'
pod 'SwiftProtobuf', '1.20.3'
end
